[package]
name = "alto-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
alto-storage = { workspace = true }
alto-actions = { workspace = true }
#alto-storage = { path = "../storage" }
#alto-actions = { path = "../actions" }
