[package]
name = "alto-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
alto-types = { workspace = true }
commonware-cryptography = { workspace = true }
rand = "0.8.5"
rocksdb = "0.23.0"
commonware-codec = { version = "0.0.43" }
bytes = "1.7.1"
tempfile = "3.18.0"